---
title: "Project 1"
author: "SID1 SID2 SID3 SI4 SID5"
subtitle: "Task2: Practise for Project 2"
date: "University of Sydney | Day Month Year"
output:
  html_document:
    fig_caption: yes
    number_sections: yes
    self_contained: yes
    theme: flatly
    toc: true
    toc_depth: 3
    toc_float: true
    code_folding: hide
---

<br>

## Initial Data Analysis (IDA) {-}

```{r}
# LOAD DATA
diet = read.csv("Project1Data.csv")
str(diet)
```

<br>

## Produce your own plot {-}

```{r}
library(ggplot2)

plot <- ggplot(diet, aes(x=Height, y=Weight)) +
  geom_point() +
  stat_smooth()
plot
```

<br>

## Does an individual's occupation effect how often they eat breakfast? {-}

```{r}
plot1 <- ggplot(diet, aes(x=Breakfast, fill=Employment)) + 
  geom_bar() + 
  xlab("Number of days per week breakfast is consumed") +
  ylab("Frequency") +
  labs(title="Breakfast Habits vs Employment Status") +
  theme(text=element_text(size=11),
        plot.title=element_text(size=15))
plot1
```

<br>

## Is there a relationship between cooking meals and weight? {-}


```{r}
plot2 <- ggplot(diet, aes(x=Weight, y=CookMeals)) + 
  geom_boxplot() + 
  xlab("Weight of person") +
  ylab("Number of days cooks meals") +
  labs(title="Weight of Person by Cooking Meals Status")

plot2
```




